### ISSUE TITLE
does this project have digital io output block?

### ISSUE THREAD

**Issue by seuliang** [analogdevicesinc/gr-m2k#10]
I want to output heigh or low volt through digital io by bits in byte stream at same time.
so does this project have digital io output block?

**Comment by teoperisanu** [comment]
Hi,

for the moment there is no digital output block. We are going to add this block in the future, but I cannot tell exactly when. An alternative is to use gr-iio (https://github.com/analogdevicesinc/gr-iio), namely the device_sink block. Also you will need to use attr_sink to set the channels in output mode. If you are interested in using gr-iio I can explain you the structure of the flow-graph in more detail.

Thank you,
Teo

**Comment by seuliang** [comment]
Hi, teo
since two dac channel can output at same time and what's i need now is two channel output,
I will try DAC block first.
Thank you, very helpful.

Alfred

**Comment by teoperisanu** [comment]
Are there any other issues we could help you with? If not I will close this issue.

**Comment by seuliang** [comment]
hi,teo
I want to know more about  using gr-iio to output digital signal.
I'm working on writing block that unpack byte stream to two stream to feed DAC block.
thank you.
liang.

**Comment by teoperisanu** [comment]
I added a digital out sink block for gr-m2k. You can find it here: https://github.com/analogdevicesinc/gr-m2k/tree/digital_out_sink. If you encounter any problems please tell us.

**Comment by seuliang** [comment]
Thank you.
I have tried the M2K Digital Out Sink block. It works well with Vector Source Block with "short" type output. 
But when using "byte" type input, I use the "Char To Short" block to convert "byte" type to "short" type,  then I can't get digital output!

**Comment by teoperisanu** [comment]
'Char To Short' block will shift each sample to the left with 8 positions. This means that the fist 8 channels will always output 0. Furthermore the channels indexing will no longer correspond to their initial state. For example if you want you output a signal on channel 0, after the conversion, the signal will be outputted on channel 8 (only if channel 8 is enabled).
I recommend you to use the source block that outputs short values.

**Comment by seuliang** [comment]
Yes, you are right. I can get output from channel 8.
How can I forget it.
That solve my problem.

Thank you very much!
