### ISSUE TITLE
M2k Analog Out Sink output at same time ?

### ISSUE THREAD

**Issue by seuliang** [analogdevicesinc/gr-m2k#11]
I need to output voltage through two DAC channel at same time.
but from the introduction page, m2k analog out sink can output through two channel.
I want to know can I set up two dac outputing at same time ?
If can, how to set it.

with regards

**Comment by teoperisanu** [comment]
Hi,

the two channels of analog_out_sink are actually two DACs and both will be synchronized if you will use the same block for output and set sync_channels=true. Here is an example: https://github.com/analogdevicesinc/gr-m2k/blob/master/m2k-examples/m2k_analog.grc.
Please let us know if there are any problems.

Thank you,
Teo

**Comment by seuliang** [comment]
hi, teo
bother again.
Thank you.

Alfred

**Comment by teoperisanu** [comment]
Are there any other issues we could help you with? If not I will close this issue.
