### ISSUE TITLE
Can ADALM2000 operate with ADI DAC device through it's digital io

### ISSUE THREAD

**Issue by seuliang** [analogdevicesinc/gr-m2k#14]
hi,
I want to know can I use ADALM2000's digital io to control ADI dac with spi / LVDS / Parallel interface?
since I want to get different output voltage range with ADI DAC evaluation board.

Alfred

**Comment by teoperisanu** [comment]
Hi,

gr-m2k does not provide at this moment any support for controlling the digital interface in such way, but libm2k does. You can find more information on our wiki page (https://wiki.analog.com/university/tools/m2k/libm2k/digital_communication).
Also some examples are available at:
- C++: https://github.com/analogdevicesinc/libm2k/blob/master/tools/communication/examples/spi/main.cpp
- Python: https://github.com/analogdevicesinc/libm2k/blob/master/bindings/python/examples/spi.py
Is this what are you looking for?
Feel free to ask any other questions on our github pages or on the engineer zone (https://ez.analog.com/adieducation/university-program/).

Thank you,
Teo Perisanu

**Comment by teoperisanu** [comment]
Are there any other issues we could help you with?

**Comment by teoperisanu** [comment]
You can reopen the issue if you have any question.
