### ISSUE TITLE
Enable integration with Radioconda

### ISSUE THREAD

**Issue by Modiug** [analogdevicesinc/gr-m2k#22]
I had asked Ryan Volz of RadioConda to include gr-m2k (https://github.com/conda-forge/gnuradio-feedstock/issues/155) and his reply was:
- that he would prefer GnuRadio 3.10 compatibility (ok, I see there is already a branch there)
- and that conda-forge requires the package having a versioned release

So, could a 3.10 versioned release be made?

Kind Regards
Guido

**Comment by AlexandraTrifan** [comment]
Hi, 

After we run some more tests and add the changes discussed in the other issue thread we will create a release tag for the 3.10 compatible version. 
We can follow-up on the conda-forge/gnuradio-feedstock thread after the release is done.

Thank you!
-Alexandra

**Comment by Modiug** [comment]
Much appreciated!

Guido

**Comment by Modiug** [comment]
Is integrated into Radioconda already for a while. Thanks again!
